-- 001_init.sql
-- Alustava skeema NHL-projektille (teams + games)

BEGIN;

-- --------------------------------------------------------------------
-- Taulu: teams
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS teams (
    team_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL,
    abbreviation TEXT NOT NULL,
    city         TEXT,
    conference   TEXT,
    division     TEXT
);

-- UNIQUENESS abbreviationille, jotta Python-skriptin
-- ON CONFLICT (abbreviation) -logiikka toimii
ALTER TABLE teams
    ADD CONSTRAINT teams_abbreviation_key UNIQUE (abbreviation);


-- --------------------------------------------------------------------
-- Taulu: games
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS games (
    game_id      BIGINT PRIMARY KEY,
    season       TEXT,
    game_type    INTEGER,      -- esim. 2 = runkosarja, 3 = playoff (NHL-koodi)
    game_date    TIMESTAMPTZ,  -- startTimeUTC -> aikaleima UTC-ajassa
    home_team_id INTEGER NOT NULL,
    away_team_id INTEGER NOT NULL,
    home_score   INTEGER,
    away_score   INTEGER,
    venue        TEXT
);

-- --------------------------------------------------------------------
-- Ulkoavaimet (FOREIGN KEY) games -> teams
-- --------------------------------------------------------------------
ALTER TABLE games
    ADD CONSTRAINT games_home_team_id_fkey
        FOREIGN KEY (home_team_id) REFERENCES teams(team_id);

ALTER TABLE games
    ADD CONSTRAINT games_away_team_id_fkey
        FOREIGN KEY (away_team_id) REFERENCES teams(team_id);


-- --------------------------------------------------------------------
-- Indeksit suorituskykyä varten (valinnaiset, mutta suositeltavat)
-- --------------------------------------------------------------------

-- Haku peleistä päivämäärän mukaan
CREATE INDEX IF NOT EXISTS idx_games_game_date
    ON games (game_date);

-- Haku peleistä koti-/vierasjoukkueen mukaan
CREATE INDEX IF NOT EXISTS idx_games_home_team_id
    ON games (home_team_id);

CREATE INDEX IF NOT EXISTS idx_games_away_team_id
    ON games (away_team_id);


COMMIT;
